CRITICAL - 2023-10-15 20:51:25 --> Invalid file: "templates/header.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(214): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('templates/header.php')
 2 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('templates/header', [], true)
 3 APPPATH\Controllers\Home.php(10): view('templates/header')
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-15 20:54:48 --> Config\App::$baseURL is invalid.
in SYSTEMPATH\HTTP\SiteURI.php on line 197.
 1 SYSTEMPATH\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 2 SYSTEMPATH\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 3 SYSTEMPATH\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
 5 SYSTEMPATH\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 8 SYSTEMPATH\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
10 SYSTEMPATH\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', [])
11 SYSTEMPATH\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
12 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
13 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
14 SYSTEMPATH\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
15 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
16 SYSTEMPATH\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
17 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
18 SYSTEMPATH\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
19 SYSTEMPATH\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
20 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-15 20:54:48 --> Uncaught CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL is invalid. in D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURI.php:197
Stack trace:
#0 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#12 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#13 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(519): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#14 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#15 D:\projetos\xampp8.2\htdocs\ci4\system\Debug\Exceptions.php(135): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#16 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\ConfigException))
#17 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\ConfigException
Config\App::$baseURL is invalid.
#0 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#12 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#13 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#14 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#15 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#16 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#17 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#18 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
#19 D:\projetos\xampp8.2\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#20 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 197.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-15 20:55:07 --> Config\App::$baseURL is invalid.
in SYSTEMPATH\HTTP\SiteURI.php on line 197.
 1 SYSTEMPATH\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 2 SYSTEMPATH\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 3 SYSTEMPATH\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
 5 SYSTEMPATH\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 8 SYSTEMPATH\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
10 SYSTEMPATH\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', [])
11 SYSTEMPATH\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
12 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
13 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
14 SYSTEMPATH\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
15 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
16 SYSTEMPATH\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
17 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
18 SYSTEMPATH\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
19 SYSTEMPATH\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
20 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-15 20:55:07 --> Uncaught CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL is invalid. in D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURI.php:197
Stack trace:
#0 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#12 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#13 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(519): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#14 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#15 D:\projetos\xampp8.2\htdocs\ci4\system\Debug\Exceptions.php(135): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#16 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\ConfigException))
#17 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\ConfigException
Config\App::$baseURL is invalid.
#0 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURI.php(143): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURI.php(98): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURIFactory.php(222): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 D:\projetos\xampp8.2\htdocs\ci4\system\HTTP\SiteURIFactory.php(43): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(798): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(791): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(565): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(523): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#12 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#13 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(558): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#14 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#15 D:\projetos\xampp8.2\htdocs\ci4\system\Config\Services.php(538): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#16 D:\projetos\xampp8.2\htdocs\ci4\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#17 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(639): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#18 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->getRequestObject()
#19 D:\projetos\xampp8.2\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#20 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 197.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-10-15 21:12:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\projetos\xampp8.2\htdocs\ci4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\projetos\xampp8.2\htdocs\ci4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 D:\projetos\xampp8.2\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\projetos\xampp8.2\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\projetos\xampp8.2\htdocs\ci4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\projetos\xampp8.2\htdocs\ci4\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 D:\projetos\xampp8.2\htdocs\ci4\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\projetos\xampp8.2\htdocs\ci4\app\Controllers\Clientes.php(19): CodeIgniter\BaseModel->findAll()
#7 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(919): App\Controllers\Clientes->index()
#8 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Clientes))
#9 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\projetos\xampp8.2\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\projetos\xampp8.2\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\projetos\xampp8.2\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\projetos\xampp8.2\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\projetos\xampp8.2\htdocs\ci4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\projetos\xampp8.2\htdocs\ci4\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 D:\projetos\xampp8.2\htdocs\ci4\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\projetos\xampp8.2\htdocs\ci4\app\Controllers\Clientes.php(19): CodeIgniter\BaseModel->findAll()
#6 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(919): App\Controllers\Clientes->index()
#7 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Clientes))
#8 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\projetos\xampp8.2\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-10-15 21:12:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `clientes`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Clientes.php(19): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Clientes->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Clientes))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-15 21:12:33 --> Uncaught Error: Call to undefined method CodeIgniter\Debug\ExceptionHandler::cleanPath() in D:\projetos\xampp8.2\htdocs\ci4\app\Views\errors\html\error_exception.php:33
Stack trace:
#0 D:\projetos\xampp8.2\htdocs\ci4\system\Debug\BaseExceptionHandler.php(241): include()
#1 D:\projetos\xampp8.2\htdocs\ci4\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#2 D:\projetos\xampp8.2\htdocs\ci4\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500, 'D:\\projetos\\xam...')
#3 D:\projetos\xampp8.2\htdocs\ci4\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Database\Exceptions\DatabaseException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 8)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
【Previous Exception】
CodeIgniter\Database\Exceptions\DatabaseException
Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\projetos\xampp8.2\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\projetos\xampp8.2\htdocs\ci4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 D:\projetos\xampp8.2\htdocs\ci4\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#3 D:\projetos\xampp8.2\htdocs\ci4\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#4 D:\projetos\xampp8.2\htdocs\ci4\app\Controllers\Clientes.php(19): CodeIgniter\BaseModel->findAll()
#5 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(919): App\Controllers\Clientes->index()
#6 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Clientes))
#7 D:\projetos\xampp8.2\htdocs\ci4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\projetos\xampp8.2\htdocs\ci4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
in APPPATH\Views\errors\html\error_exception.php on line 33.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2023-10-15 21:12:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-15 21:12:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-10-15 21:13:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
